categories: [Metagenomics]
description: Contains a suite of tools for analyzing metagenomics data.
name: suite_test
type: repository_suite_definition
remote_repository_url: https://github.com/cdeanj/galaxytools/tree/master/suites/suite_test
owner: chrisd
